# Generated by Django 3.2.9 on 2021-12-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20211201_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
