# Generated by Django 3.2.9 on 2021-12-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default1.jpeg', null=True, upload_to='images'),
        ),
    ]
