# Generated by Django 3.2.9 on 2021-12-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
